#!/bin/bash

set -e

VERSION=$(grep -i "Stable tag:" readme.txt | awk -F' ' '{print $NF}' | tr -d '\r')

wp-pot \
  --domain wpdr-email-notice \
  --dest-file languages/wpdr-email-notice.pot \
  --src "wpdr-email-notice.php" --src "includes/*.php" \
  --package "WP Document Revisions Email Notice $VERSION" --relative-to "." \
  --comment-keyword "translators:"
