# Based on https://github.com/wordpress/wp-plugin-dependencies
name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  phpcs:
    runs-on: ubuntu-latest
    env:
      TRAVIS_BUILD_DIR: ${{ github.workspace }}
    strategy: 
      matrix:
        php_version: [7.4]
    steps:
      - uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php_version }}
          extensions: mysqli

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v3
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ matrix.php_version }}-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-${{ matrix.php_version }}-

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-suggest
      
      - name: phpcs
        run: script/cibuild-phpcs
