name: Generate POT file

on:
  workflow_dispatch:
    branches: [main]

jobs:
  generate-pot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Install WP-POT-CLI
        run: npm install --global wp-pot-cli

      - name: Generate POT file
        run: script/generate-pot

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
            commit-message: "Update POT file"
            title: "Update POT file"
